<?php
if (!defined('ABSPATH')) {
    exit;
}

class WpPopPop_Addon_WooCommerce {
    public function __construct() {
        if (!class_exists('WooCommerce')) {
            return;
        }
        add_action('wp_ajax_wppoppop_apply_wc_coupon', [$this, 'ajax_apply_wc_coupon']);
        add_action('wp_ajax_nopriv_wppoppop_apply_wc_coupon', [$this, 'ajax_apply_wc_coupon']);
    }

    public function generate_wc_coupon(array $args) {
        if (!class_exists('WooCommerce')) {
            return false;
        }

        $code_prefix  = !empty($args['prefix']) ? sanitize_key($args['prefix']) : 'POP';
        $discount_type = !empty($args['type']) ? sanitize_key($args['type']) : 'percent'; // percent, fixed_cart, fixed_product
        $amount       = floatval($args['amount'] ?? 10);
        $coupon_code  = strtoupper($code_prefix . '_' . wp_generate_password(8, false));

        $coupon = new WC_Coupon();
        $coupon->set_code($coupon_code);
        $coupon->set_discount_type($discount_type);
        $coupon->set_amount($amount);
        $coupon->set_individual_use(true);
        $coupon->set_usage_limit(1);
        $coupon->set_description('Generated by WpPopPop campaign');

        if (!empty($args['expiry_days'])) {
            $expiry = (new DateTime())->modify('+' . intval($args['expiry_days']) . ' days');
            $coupon->set_date_expires($expiry->getTimestamp());
        }

        $coupon->save();

        wppoppop_log_event('wc_coupon_created', 'Created coupon: ' . $coupon_code, [
            'amount' => $amount,
            'type'   => $discount_type
        ]);

        return $coupon_code;
    }

    public function auto_apply_wc_coupon($coupon_code) {
        if (!class_exists('WooCommerce') || !function_exists('WC') || !WC()->cart) {
            return false;
        }

        if (!WC()->cart->has_discount($coupon_code)) {
            return WC()->cart->add_discount(sanitize_text_field($coupon_code));
        }
        return true;
    }

    public function ajax_apply_wc_coupon() {
        check_ajax_referer('wppoppop_front_nonce', 'nonce');
        $code = isset($_POST['coupon_code']) ? sanitize_text_field($_POST['coupon_code']) : '';
        if (empty($code)) {
            wp_send_json_error(['message' => 'Missing coupon code.']);
        }

        $applied = $this->auto_apply_wc_coupon($code);
        if ($applied) {
            wp_send_json_success(['message' => 'Coupon applied to cart successfully!']);
        } else {
            wp_send_json_error(['message' => 'Unable to apply coupon to cart.']);
        }
    }

    public function matches_cart_conditions(array $woo_rules) {
        if (!class_exists('WooCommerce') || !function_exists('WC') || !WC()->cart) {
            return true;
        }

        $cart_subtotal = floatval(WC()->cart->get_subtotal());
        if (!empty($woo_rules['min_cart_total']) && $cart_subtotal < floatval($woo_rules['min_cart_total'])) {
            return false;
        }
        if (!empty($woo_rules['max_cart_total']) && $cart_subtotal > floatval($woo_rules['max_cart_total'])) {
            return false;
        }

        return true;
    }
}
